{
 "title": "PT Trex BTC",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Profit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT dt AS time\n  , profit_c\nFROM trex.dash002_tracker_logs_004_profits \nWHERE $__timeFilter(dt)\nORDER BY dt\n"
    }
   ]
  },
  {
   "title": "Current Positions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT created_at AS time\n  , balance + totalPairsCurrentValue + totalDCACurrentValue + totalPendingCurrentValue \"Total Current Value\"\nFROM trex.hist_totals\nORDER BY created_at\n"
    },
    {
     "rawSql": "SELECT created_at AS time\n  , totalPairsCurrentValue \"Total Pairs Value\"\nFROM trex.hist_totals\nORDER BY created_at\n\n"
    },
    {
     "rawSql": "SELECT created_at AS time\n  , totalDCACurrentValue \"Total DCA Value\"\nFROM trex.hist_totals\nORDER BY created_at\n\n"
    }
   ]
  },
  {
   "title": "Unrealised PnL Today",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT Unrealised_PnL\nFROM trex.dash002_tracker_logs_004_profits \nWHERE dt = CURRENT_DATE\n/*\n   SELECT (SELECT profit_c FROM trex.dash002_tracker_logs_004_profits WHERE dt = CURRENT_DATE)\n  - COALESCE((\n    SELECT SUM(avg_avgCost - avg_totalAmount*currentPrice)\n    FROM trex.hist_dca h\n    WHERE h.created_at = (SELECT started_at FROM trex.logs ORDER BY started_at DESC LIMIT 1)\n  ),0)\n  - COALESCE((\n    SELECT SUM(avg_avgCost - avg_totalAmount*currentPrice)\n    FROM trex.hist_gains h\n    WHERE h.created_at = (SELECT started_at FROM trex.logs ORDER BY started_at DESC LIMIT 1)\n  ),0) \n*/"
    }
   ]
  },
  {
   "title": "Unrealised PnL All time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\nCOALESCE((SELECT SUM(profit_c) FROM trex.dash002_tracker_logs_004_profits WHERE dt < CURRENT_DATE),0)\n+ COALESCE((SELECT Unrealised_PnL FROM trex.dash002_tracker_logs_004_profits WHERE dt = CURRENT_DATE),0)\n/*\nSELECT \n  (SELECT SUM(profit_c) FROM trex.dash002_tracker_logs_004_profits)\n  - COALESCE((\n    SELECT SUM(avg_avgCost - avg_totalAmount*currentPrice)\n    FROM trex.hist_dca h\n    WHERE h.created_at = (SELECT started_at FROM trex.logs ORDER BY started_at DESC LIMIT 1)\n  ),0)\n  - COALESCE((\n    SELECT SUM(avg_avgCost - avg_totalAmount*currentPrice)\n    FROM trex.hist_gains h\n    WHERE h.created_at = (SELECT started_at FROM trex.logs ORDER BY started_at DESC LIMIT 1)\n  ),0)\n  */"
    }
   ]
  },
  {
   "title": "Unrealised PnL Today(GBP)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT Unrealised_PnL_GBP\nFROM trex.dash002_tracker_logs_004_profits \nWHERE dt = CURRENT_DATE\n"
    }
   ]
  },
  {
   "title": "Unrealised PnL All time(GBP)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT (\n  COALESCE((SELECT SUM(profit_c) FROM trex.dash002_tracker_logs_004_profits WHERE dt < CURRENT_DATE),0)\n  + COALESCE((SELECT Unrealised_PnL FROM trex.dash002_tracker_logs_004_profits WHERE dt = CURRENT_DATE),0)\n)*(SELECT GBP FROM trex.dash002_tracker_logs_004_profits ORDER BY dt DESC LIMIT 1)\n"
    }
   ]
  },
  {
   "title": "Pairs Open Positions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(avg_cost)\nFROM trex.dash002_tracker_logs_002_pairs\n"
    }
   ]
  },
  {
   "title": "DCA Open positions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(avg_cost)\nFROM trex.dash002_tracker_logs_001_dca\n"
    }
   ]
  },
  {
   "title": "Pairs Open Positions(GBP)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT GBP*(\n  SELECT SUM(avg_cost)\n  FROM trex.dash002_tracker_logs_002_pairs\n)\nFROM trex.dash002_tracker_logs_004_profits \nWHERE dt = CURRENT_DATE\n"
    }
   ]
  },
  {
   "title": "DCA Open positions(GBP)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT GBP*(\n  SELECT SUM(avg_cost)\n  FROM trex.dash002_tracker_logs_001_dca\n  )\nFROM trex.dash002_tracker_logs_004_profits \nWHERE dt = CURRENT_DATE\n"
    }
   ]
  },
  {
   "title": "Profit All Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(profit_c) week_profit_c\nFROM trex.dash002_tracker_logs_004_profits \n"
    }
   ]
  },
  {
   "title": "Profit All Time(GBP)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT SUM(profit_c)*(SELECT GBP FROM trex.dash002_tracker_logs_004_profits ORDER BY dt DESC LIMIT 1)\nFROM trex.dash002_tracker_logs_004_profits \n"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN dt = current_date THEN 'Today' ELSE to_char(dt,'Mon DD') END \"Date\"\n  , nbr_trans \"# Trans.\"\n  , ROUND(profit_c,5) \"Profit\"\n  , ROUND(profit_c*(SELECT GBP FROM trex.dash002_tracker_logs_004_profits ORDER BY dt DESC LIMIT 1),2) \"Profit(GBP)\"\n  , ROUND(profit_c*100/NULLIF((SELECT total_current_value FROM trex.dash002_tracker_logs_004_profits pr ORDER BY dt DESC LIMIT 1),0),2) \"Profit(%)\"\nFROM trex.dash002_tracker_logs_004_profits pr\nORDER BY dt DESC"
    }
   ]
  },
  {
   "title": "Weekly",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT to_char(DATE_TRUNC('week', dt),'Mon DD\" (Week \" W)') \"Week\"\n  , SUM(nbr_trans) \"# Trans.\"\n  , ROUND(SUM(profit_c),5) \"Profit\"\n  , ROUND(SUM(profit_c)*(SELECT GBP FROM trex.dash002_tracker_logs_004_profits ORDER BY dt DESC LIMIT 1),2) \"Profit(GBP)\"\n  , ROUND(SUM(profit_c)*100/NULLIF((SELECT total_current_value FROM trex.dash002_tracker_logs_004_profits pr ORDER BY dt DESC LIMIT 1),0),2) \"Profit(%)\"\nFROM trex.dash002_tracker_logs_004_profits pr\nGROUP BY DATE_TRUNC('week', dt)\nORDER BY DATE_TRUNC('week', dt) DESC"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT to_char(DATE_TRUNC('month', dt),'Mon YYYY') \"Month\"\n  , SUM(nbr_trans) \"# Trans.\"\n  , ROUND(SUM(profit_c),5) \"Profit\"\n  , ROUND(SUM(profit_c)*(SELECT GBP FROM trex.dash002_tracker_logs_004_profits ORDER BY dt DESC LIMIT 1),2) \"Profit(GBP)\"\n  , ROUND(SUM(profit_c)*100/NULLIF((SELECT total_current_value FROM trex.dash002_tracker_logs_004_profits pr ORDER BY dt DESC LIMIT 1),0),2) \"Profit(%)\"\nFROM trex.dash002_tracker_logs_004_profits pr\nGROUP BY DATE_TRUNC('month', dt)\nORDER BY DATE_TRUNC('month', dt) DESC"
    }
   ]
  },
  {
   "title": "Current DCA Log",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT coin \"Coin\"\n  , dca_level \"DCA Level\"\n  , gain_loss \"Gain/Loss\"\n  , avg_price \"Avg Price\"\n  , avg_cost \"Cost\"\n  , ROUND(days_in_dca) \"Days in DCA\"\n  , current_price \"Current Price\"\n  , sell_strategy \"Sell Strategy\"\n  , profit_sell_trigger \"Profit Sell Trigger\"\n  , daily_change \"Daily Change\"\nFROM trex.dash002_tracker_logs_001_dca\nORDER BY coin"
    }
   ]
  },
  {
   "title": "Sell Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT soldDate \"Sell Date\"\n  , market \"Coin\"\n  , soldAmount \"Qty\"\n  , dca_level \"DCA Level\"\n  , profit \"Profit\"\n  , avg_price \"Avg Price\"\n  , avg_cost \"Avg Cost\"\n  , first_purchased \"First Purchased\"\n  , currentPrice \"Sell Price\"\n  , sell_strategy \"Sell Strategy\"\n  , sell_trigger \"Sell Trigger\"\n  , fee \"Fee\"\nFROM trex.dash002_tracker_logs_003_sell\nORDER BY soldDate\n  , market"
    }
   ]
  },
  {
   "title": "Current Pairs Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT coin \"Coin\"\n  --, dca_level \"DCA Level\"\n  , gain_loss \"Gain/Loss\"\n  --, avg_price \"Avg Price\"\n  , avg_cost \"Cost\"\n  --, ROUND(days_in_dca) \"Days in DCA\"\n  , current_price \"Current Price\"\n  , sell_strategy \"Sell Strategy\"\n  , profit_sell_trigger \"Profit Sell Trigger\"\n  , daily_change \"Daily Change\"\nFROM trex.dash002_tracker_logs_002_pairs\nORDER BY coin"
    }
   ]
  }
 ]
}